version: '3.9'

networks:
  app-network:
    driver: bridge

services:

  # ASP.NET Core Web API Application
  costume-webapi:
    image: ${DOCKER_REGISTRY-}costume-webapi
    container_name: costume-webapi
    restart: always
    build:
      context: .
      dockerfile: src/costume.PublicApi/Dockerfile
    expose:
      - 80
    links:
      - costume-sql-server
      - costume-mongo-server
      - costume-redis
    networks:
      - app-network
    depends_on:
      - costume-sql-server
      - costume-mongo-server
      - costume-redis

  # SQL Server
  costume-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: costume-sql-server
    restart: always
    expose:
      - 1434
    ports:
      - "1434:1434"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pMA63033n6tF
    networks:
      - app-network

  # MongoDB Server
  costume-mongo-server:
    image: mongo:4.4
    container_name: costume-mongo-server
    restart: always
    expose:
      - 27019
    ports:
      - "27019:27019"
    networks:
      - app-network

  # Redis Cache Server
  costume-redis:
    image: redis:latest
    container_name: costume-redis
    command: redis-server --requirepass pMA63033n6tF
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - app-network
